[package]
name = "luma_lexer"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
luma_core = { workspace = true }
luma_diagnostic = { workspace = true }