[package]
name = "luma_vm"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
luma_core = { workspace = true }
luma_parser = { workspace = true }
luma_diagnostic = { workspace = true }